version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 111111112
      MYSQL_DATABASE: myDB
      MYSQL_USER: root
      MYSQL_PASSWORD: 111111112
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
    mem_limit: 400m  # Memory allocation for MySQL (200 MB)

  app:
    build: .
    container_name: node_app_container
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 111111112
      DB_NAME: myDB
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynetwork
    mem_limit: 150m  # Memory allocation for Node Server (100 MB)

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/nginx/certs  # Mount the host system's certificate directory
    depends_on:
      - app
    networks:
      - mynetwork
    mem_limit: 41m  # Memory allocation for Nginx Proxy (20 MB)

networks:
  mynetwork:

volumes:
  db_data:
