version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 88888888
      MYSQL_DATABASE: myDB
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    # Memory allocation for MySQL (200 MB)
    mem_limit: 200m

  app:
    build: .
    container_name: node_app_container
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 88888888
      DB_NAME: myDB
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynetwork
    # Memory allocation for Node Server (100 MB)
    mem_limit: 100m

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - mynetwork
    # Memory allocation for Nginx Proxy (20 MB)
    mem_limit: 20m

  certbot:
    image: certbot/certbot
    container_name: certbot_container
    volumes:
      - ./certs:/etc/letsencrypt
    depends_on:
      - nginx
    networks:
      - mynetwork
    # Memory allocation for Certbot (100 MB)
    mem_limit: 100m

networks:
  mynetwork:

volumes:
  db_data:

